backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }
